USE homes

CREATE TABLE IF NOT EXISTS address (
  id INT unsigned NOT NULL AUTO_INCREMENT,
  address varchar(100) NOT NULL,
  PRIMARY KEY (id)
);


CREATE TABLE `tours` (
	id INT(9) UNSIGNED NOT NULL AUTO_INCREMENT,
	home_id INT(9) UNSIGNED NOT NULL,
	financing VARCHAR(255) NOT NULL,
  name VARCHAR(100) NOT NULL,
	timeslot VARCHAR(50) NOT NULL,
	phone VARCHAR(255) NOT NULL,
	email VARCHAR(100) NOT NULL,
	tour_type VARCHAR(255) NOT NULL,
	day VARCHAR(255) NOT NULL,
  PRIMARY KEY(`id`)
);